# POST http://localhost:7000/savepost
# Content-Type: application/json

# {   
#     "text": "workout"
# }

GET http://localhost:7000/gettask

//PUT http://localhost:7000/update/20eb0dbe-0d5c-49fc-8260-fc2a9404ea3a


//DELETE http://localhost:7000/delete/724b181a-dc71-41c0-9f02-bc6cd1920748